// flow-typed signature: 57d5a939f6b158da35bb86c0fbec1f97
// flow-typed version: <<STUB>>/isomorphic-mapzen-search_v^1.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-mapzen-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-mapzen-search' {
  declare export type MapzenResult = {
    geometry: {
      coordinates: [number, number]
    },
    properties: {
      label: string,
      postalcode?: string
    }
  }

  declare export type IMSResponse = {
    features?: Array<MapzenResult>,
    isomorphicMapzenSearchQuery: Object
  }

  declare export type AutocompleteParams = {
    apiKey: string,
    boundary: {
      country?: string,
      rect?: {
        minLat: number,
        minLon: number,
        maxLat: number,
        maxLon: number
      }
    },
    focusPoint?: {
      centerPoint: mixed,
      radius: number
    },
    format?: boolean,
    layers?: any,
    sources?: string,
    text: string
  }

  declare export type ReverseParams = {
    apiKey: string,
    format?: boolean,
    point: mixed
  }

  declare export function autocomplete(AutocompleteParams): Promise<IMSResponse>
  declare export function reverse(ReverseParams): Promise<IMSResponse>
}
