// flow-typed signature: b1bcad4f459d3e23e1460c8b17a4feea
// flow-typed version: <<STUB>>/lodash.throttle_v^4.1.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.throttle' {
  declare export default function throttle<T>((T) => void, number): (T) => void
}
