// flow-typed signature: 5e82d258861e15c892e1d043cd99f2fe
// flow-typed version: <<STUB>>/qs_v^6.3.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qs' {
  declare module.exports: {
    stringify(Object): string
  }
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qs/dist/qs' {
  declare module.exports: any;
}

declare module 'qs/lib/formats' {
  declare module.exports: any;
}

declare module 'qs/lib/index' {
  declare module.exports: any;
}

declare module 'qs/lib/parse' {
  declare module.exports: any;
}

declare module 'qs/lib/stringify' {
  declare module.exports: any;
}

declare module 'qs/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qs/dist/qs.js' {
  declare module.exports: $Exports<'qs/dist/qs'>;
}
declare module 'qs/lib/formats.js' {
  declare module.exports: $Exports<'qs/lib/formats'>;
}
declare module 'qs/lib/index.js' {
  declare module.exports: $Exports<'qs/lib/index'>;
}
declare module 'qs/lib/parse.js' {
  declare module.exports: $Exports<'qs/lib/parse'>;
}
declare module 'qs/lib/stringify.js' {
  declare module.exports: $Exports<'qs/lib/stringify'>;
}
declare module 'qs/lib/utils.js' {
  declare module.exports: $Exports<'qs/lib/utils'>;
}
