// flow-typed signature: 0c65e3e1ee211ae88da7fd4ae7c9bcd7
// flow-typed version: <<STUB>>/react-native-lock_v^0.6.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare class Lock {
  show(
    {
      authParams: {
        scope: string
      },
      closable: boolean
    },
    (err: Error, profile: Object, token: Object) => void
  ): void
}

declare module 'react-native-lock' {
  declare module.exports: Class<Lock>;
}
