// flow-typed signature: 3f1f01ffa9b36d8a3762d933b66d73f4
// flow-typed version: <<STUB>>/react-native-html-parser_v^0.0.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-html-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-html-parser' {
  declare type Attribute = {
    name: string,
    value: string
  }

  declare type Node = {
    attributes: Array<Attribute>,
    childNodes: Array<Node>,
    data: string,
    nodeName: string
  }

  declare type DOC = {
    childNodes: Array<Node>
  }

  declare class DOMParser {
    parseFromString(string, string): DOC
  }

  declare module.exports: {
    DOMParser: Class<DOMParser>
  }
}
