// flow-typed signature: 57d5a939f6b158da35bb86c0fbec1f97
// flow-typed version: <<STUB>>/isomorphic-mapzen-search_v^1.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-mapzen-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

type FocusPoint = {
  centerPoint: mixed,
  radius: number
}

type BaseQuery = {
  clientId?: string,
  clientSecret?: string,
  url?: string
}

declare module '@conveyal/geocoder-arcgis-geojson' {
  declare export type AutocompleteResult = {
    magicKey: string,
    text: string
  }

  declare export type MapzenResult = {
    geometry: {
      coordinates: [number, number]
    },
    properties: {
      label: string,
      postalcode?: string
    }
  }

  declare export type AutocompleteResponse = {
    features?: Array<AutocompleteResult>,
    query: Object
  }

  declare export type IMSResponse = {
    features?: Array<MapzenResult>,
    query: Object
  }

  declare export type AutocompleteParams = BaseQuery & {
    boundary?: {
      rect?: {
        minLat: number,
        minLon: number,
        maxLat: number,
        maxLon: number
      }
    },
    focusPoint?: FocusPoint,
    text: string
  }

  declare export type ReverseParams = BaseQuery & {
    point: mixed
  }

  declare export type SearchParams = BaseQuery & {
    boundary?: {
      rect?: {
        minLat: number,
        minLon: number,
        maxLat: number,
        maxLon: number
      }
    },
    focusPoint?: FocusPoint,
    size?: number,
    sources?: string,
    text: string
  }

  declare export function autocomplete(AutocompleteParams): Promise<{
    features?: Array<{
      magicKey: string,
      text: string
    }>,
    query: Object
  }>
  declare export function reverse(ReverseParams): Promise<IMSResponse>
  declare export function search(SearchParams): Promise<IMSResponse>
}
